version: '3.4'

services:
  wcfclientccccc:
    image: ${DOCKER_REGISTRY-}wcfclientccccc
    build:
      context: .\WcfClientCCCCC
      dockerfile: Dockerfile
    environment:
      - runninngEnv=docker
    networks:
      wcfsamplenetwork:
        ipv4_address: 197.168.10.11
    depends_on:
      - wcfserverttttt02

  wcfclientrrrrr:
    image: ${DOCKER_REGISTRY-}wcfclientrrrrr
    build:
      context: .\WcfClientRRRRR
      dockerfile: Dockerfile
    environment:
      - runninngEnv=docker
    networks:
      wcfsamplenetwork:
        ipv4_address: 197.168.10.12
    depends_on:
      - wcfserverttttt02

  wcfserverttttt01:
    image: ${DOCKER_REGISTRY-}wcfserverttttt01
    build:
      context: .\WcfServerTTTTT01
      dockerfile: Dockerfile
    environment:
      - runninngEnv=docker
    networks:
      wcfsamplenetwork:
        ipv4_address: 197.168.10.13

  wcfserverttttt02:
    image: ${DOCKER_REGISTRY-}wcfserverttttt02
    build:
      context: .\WcfServerTTTTT02
      dockerfile: Dockerfile
    environment:
      - runninngEnv=docker
    networks:
      wcfsamplenetwork:
        ipv4_address: 197.168.10.14
    depends_on:
      - wcfserverttttt01

networks:
  wcfsamplenetwork:
    driver: nat
    ipam:
      driver: default
      config:
        - subnet: 197.168.10.0/24    
